language: cpp

compiler:
  - g++
  - clang

branches:
  except:
    - gh-pages

before_install:
  - sudo apt-get update
  - sudo apt-get install -y librados-dev lua5.2 lua5.2-dev

install:
  - autoreconf -I m4 -ivf
  - ./configure
  - make

script: "exit 0"

notifications:
  recipients:
    - noahwatkins@gmail.com
  email:
    on_success: always
    on_failure: always

sudo: required 
services:   
  - docker
